[package]
name = "mk_file_config_derive"
version = "0.1.0"
edition = "2021"
description = "Derive library for mk_file_config"
readme = "README.md"

[dependencies]
syn = "^2.0.0"
quote = "^1.0.0"
proc-macro2 = "^1.0.0"

[lib]
proc-macro = true
